name: Defang CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Checkout defang
      uses: actions/checkout@v4
      with:
        repository: DefangLabs/defang
        ref: edw/interactive-login
        path: defang-src

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: defang-src/src/go.mod

    - name: Build defang
      run: |
        ls -lah
        pwd
        make build
      working-directory: defang-src/src

    - name: Run defang cd ls
      env:
        GOOGLE_WORKLOAD_IDENTITY_PROVIDER: //iam.googleapis.com/projects/979169844604/locations/global/workloadIdentityPools/defang-github/providers/github-actions-mu4q9u
      run: ./defang-src/src/defang cd ls
