name: Defang CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download defang binary
      run: |
        gh release download testoidcnocgo --repo edwardrf/testactions --pattern defang
        chmod +x defang
        ls -lah
        echo $ACTIONS_ID_TOKEN_REQUEST_URL
      env:
        GH_TOKEN: ${{ github.token }}
    - name: Defang login
      run: |
        ls -la defang
        ./defang login
        ./defang whoami
    - name: Run defang cd ls
      # env:
        # GOOGLE_WORKLOAD_IDENTITY_PROVIDER: //iam.googleapis.com/projects/979169844604/locations/global/workloadIdentityPools/defang-github/providers/github-actions-mu4q9u
        # GCP_PROJECT_ID: edw-test-samples-7
      run: |
        # mkdir -p /home/runner/.local/state/defang/
        # echo -n "eyJhbGciOiJFUzI1NiIsImtpZCI6IjEzYjExNWJmLWU5NmItNGFlNy04ZDY0LWE3NjVkNzMyZGJiNiIsInR5cCI6IkpXVCJ9.eyJtb2RlIjoiYWNjZXNzIiwidHlwZSI6InVzZXIiLCJwcm9wZXJ0aWVzIjp7ImlkIjoiNThhYzg0MzYtMDQ3ZC01NTlmLThkYTMtNzI3YjM4ZjMwMmQyIiwidGVuYW50IjoiZWR3YXJkcmYiLCJoYXN1cmEiOnsieC1oYXN1cmEtYWxsb3dlZC1yb2xlcyI6WyJ1c2VyIl0sIngtaGFzdXJhLWRlZmF1bHQtcm9sZSI6InVzZXIiLCJ4LWhhc3VyYS11c2VyLWlkIjoiNThhYzg0MzYtMDQ3ZC01NTlmLThkYTMtNzI3YjM4ZjMwMmQyIn0sImV4dGVybmFsVGVuYW50cyI6WyIzNDE1NjNlZi00OWQxLTU0YWUtODAzNC02NzJhZDM4ODFmNjciLCI0YjE2YjdhNy0xOTliLTViMzktYTA5Yy04ZTkyMWY2OGNhNjIiLCJiMGMzZDdkYS04ZmIxLTVjNmItYjQ5NC0wMmM5YjE0MzViYjciXSwiZ2l0aHViT3JncyI6WyJ4aW5jaGVqaWFuIiwiZWZvdW5kYXRpb25ib2FyZCIsIkRlZmFuZ0xhYnMiXX0sImF1ZCI6ImRlZmFuZy1jbGkiLCJpc3MiOiJodHRwczovL2F1dGguZGVmYW5nLmlvIiwic3ViIjoiNThhYzg0MzYtMDQ3ZC01NTlmLThkYTMtNzI3YjM4ZjMwMmQyIiwiZXhwIjoxNzcyNzU2MTYxfQ.KT4M3LUZzme-HaLbUPVWyxIleQ-KsM5qRn51y-gaJEpmDsKuvBVmIueG8niWpBvkykKTqLDleVCC4AlJI5AgEg" > /home/runner/.local/state/defang/fabric-prod1.defang.dev
        # ./defang-src/src/defang stack ls --debug
        ./defang cd ls --provider aws --project-name=golang-http --stack=production --debug
