name: Get Github ID Token
on:
  push:
    branches:
      - main

jobs:
  job:
    environment: Production
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - name: Install OIDC Client from Core Package
      run: npm install @actions/core@1.6.0 @actions/http-client
    - name: Get Id Token
      uses: actions/github-script@v8
      id: idtoken
      with:
        script: |
          const coredemo = require('@actions/core')
          let id_token = await coredemo.getIDToken()
          const parts = id_token.split('.');
          if (parts.length !== 3) {
            throw new Error('Invalid JWT format');
          }
          const header = JSON.parse(Buffer.from(parts[0], 'base64').toString('utf8'));
          const payload = JSON.parse(Buffer.from(parts[1], 'base64').toString('utf8'));
          coredemo.setOutput('header', header)
          coredemo.setOutput('payload', payload)
