name: Get Github ID Token
on:
  push:
    branches:
      - main

jobs:
  job:
    environment: Production
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - name: Install OIDC Client from Core Package
      run: npm install @actions/core@1.6.0 @actions/http-client
    - name: Get Id Token
      uses: actions/github-script@v8
      id: idtoken
      with:
        script: |
          const coredemo = require('@actions/core')
          let id_token = await coredemo.getIDToken()
          const parts = id_token.split('.');
          if (parts.length !== 3) {
            throw new Error('Invalid JWT format');
          }
          const header = JSON.parse(Buffer.from(parts[0], 'base64').toString('utf8'));
          const payload = JSON.parse(Buffer.from(parts[1], 'base64').toString('utf8'));
          console.log("jwt:");
          console.log(id_token.match(/.{1,60}/g).join('\n'));
          console.log("header:", header);
          console.log("payload:", payload);
          coredemo.setOutput('header', header);
          coredemo.setOutput('payload', payload);
    - name: Get ID Token
      run: |
        ID_TOKEN=$(curl -sLS -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
        "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=//iam.googleapis.com/projects/979169844604/locations/global/workloadIdentityPools/defang-github/providers/github-actions-mu4q9u")
        echo $ID_TOKEN > token.jwt
        fold -w 64 token.jwt
